### ISSUE TITLE
Comparison analysis

### ISSUE THREAD

**Issue by rgoldiez** [keen/keen-analysis.js#3]
It would be really nice if the keen SDK could handle comparison analysis.  For example, sum of some property each day this month compared to last month where day [x] from this month sits right next to day[x] from last month.  Or, the same comparison for each day this week vs. last week.  Or, by hour with today vs. yesterday.  I mocked up an excel version attached below.

I realize I can fire off 2 queries, merge the data in javascript, and run that into a chart.  Just seems like this is something that could be useful to a lot of people and the community would be benefited by having this feature built in.  

Also, I've been in touch with one of the keen support folks via Slack.  They've been very helpful and suggested I store additional properties with my event data (ie, day of week, day of month, hour, etc.).  I'm doing that now and it _kind of_ works but not straightforward, takes some work, and doesn't produce the same result as the chart below.

![untitled](https://cloud.githubusercontent.com/assets/10797610/13366818/548776d2-dca3-11e5-9a46-7ad0f04673eb.png)

**Comment by dustinlarimer** [comment]
@rgoldiez thanks for sharing! We've discussed rolling this type of grouping into the API at some point in the future, since it's certainly super valuable for the type of histogram analysis you're looking for. Storing those properties on the way in has lots of other benefits as well, as it opens the door to more flexible, multi-dimensional analysis. 

Our new tracking library [keen-tracking.js](https://github.com/keen/keen-tracking.js#datetime-index) has a built-in helper for just this sort of datetime indexing:

```javascript
client.recordEvent('pageview', {
  time: Keen.helpers.getDatetimeIndex()
});

/*
// Monday, June 29th, 2015
{
  time: {
    'hour_of_day': 14,
    'day_of_week': 2,
    'day_of_month': 29,
    'month': 6,
    'year': 2015
  }
}
*/
```

This would let you run queries with sub-groups, like "count pageviews, grouped by `day_of_week`, grouped by `hour_of_day`" to see which hours of which days of the week are the most active.

Your point about running two queries and merging the results is right on– The same query w/ diverging timeframe values of `"this_1_week"` and `"previous_1_week"` would bring back two responses that could be merged using our `Dataset` utility, bundled with `Dataviz`: https://github.com/keen/keen-dataviz.js/tree/master/lib/dataset. 

The first response can be passed straight into the chart and handled appropriately, then the second response could be parsed on its own and passed in with `dataset.appendColumn()` method, demonstrated in this jsFiddle: http://jsfiddle.net/keen/5gt8p0m3/. All-in, this would be a pretty minimal amount of code, for how much customization would be happening.

If you have date indexing set up in your data collection, I would be happy to help get a proof-of-concept running!

**Comment by rgoldiez** [comment]
@dustinlarimer - thanks for responding.  Does `getDatetimeIndex()` support target timezones?  We have customers in different timezones.  The way I accomplished the equivalent of `getDatetimeIndex()` was using `momentjs` and manipulating the event time based on our customer's specific timezone.  I'll give the `Dataset` utility a try.... your fiddle is definitely helpful.  Thanks!

**Comment by dustinlarimer** [comment]
Hey there, glad the fiddle was helpful! That helper function takes a Date
object, so I think you can create one set to the specific timezone and pass
that in. Otherwise it just creates a new local/relative "now".
