### ISSUE TITLE
GET request if second parameter is string

### ISSUE THREAD

**Issue by venil7** [keen/keen-analysis.js#9]
I'm trying to force all requests to be `GET`s, 
this line of code https://github.com/keen/keen-analysis.js/blob/master/lib/index.js#L26 sggests that second parameter should be `string`, 

I tried to `JSON.stringify({query parameters...})` as second param, but that fails,

or should I manually convert my query params to query string `?event_collection=event&...` ?

please advice

**Comment by dustinlarimer** [comment]
Hey @venil7 can you elaborate a bit on why you want all requests to be `GET`s? You could construct manual `GET` requests for a query like so:

```javascript
client
  .get(client.url('queries', 'count'))
  .auth('YOUR_READ_KEY')
  .send({
    event_collection: 'pageviews',
    timeframe: 'this_14_days'
  })
  .then(function(res){
    // do something with the result
  })
  .catch(function(err){
    // catch and handle errors
  });
```

**Comment by venil7** [comment]
I want them to be `GET`s so I can cache them on proxy layer, (this is obviously for non mutating requests)
I'm using similar construction to the one above which pretty much gets me there, only learned about it after I creted issue

**Comment by dustinlarimer** [comment]
@venil7 that seems like a great use case, though I think it would be best to stick with the pattern above for now. We might go for making the `.query()` method configurable with a global default of some kind, but we're a bit taxed for time and would like to think about it for awhile. I'm super happy to see this SDK getting some attention, and hope it's working well for you otherwise! Keep the feedback and input coming our way :)
